[package]
name = "nonblock-logger"
version = "0.0.2"
authors = ["Wspsxing <biluohc@qq.com>"]
# edition = "2018"

[features]
color = ["colored"]

[dependencies]
log = "0.4"
chrono = "0.4"
crossbeam-channel = "0.3"
colored = { version = "1.8", optional = true }
