[package]
name = "nonblock-logger"
version = "0.0.1"
authors = ["Wspsxing <biluohc@qq.com>"]
# edition = "2018"

[features]
[dependencies]
log = "0.4"
chrono = "0.4"
crossbeam = "0.7"
colored = "1.8"

