[package]
name = "feature_color"
version = "0.1.0"
authors = ["Wspsxing <biluohc@qq.com>"]
edition = "2018"

[dependencies]
# nonblock-logger = { version = "0.1", features = [ "color" ] }
nonblock-logger = { path = "../..", features = [ "color" ] }
